// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dialog

import (
	"12345/api/dialog"
)

type ControllerV1 struct{}

func NewV1() dialog.IDialogV1 {
	return &ControllerV1{}
}
