// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: pbentity/common.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_RoleNone      Role = 0
	Role_RoleSystem    Role = 1
	Role_RoleUser      Role = 2
	Role_RoleAssistant Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "RoleNone",
		1: "RoleSystem",
		2: "RoleUser",
		3: "RoleAssistant",
	}
	Role_value = map[string]int32{
		"RoleNone":      0,
		"RoleSystem":    1,
		"RoleUser":      2,
		"RoleAssistant": 3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_pbentity_common_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_pbentity_common_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_pbentity_common_proto_rawDescGZIP(), []int{0}
}

type MsgType int32

const (
	MsgType_MsgTypeNone  MsgType = 0 //
	MsgType_MsgTypeText  MsgType = 1
	MsgType_MsgTypeImage MsgType = 2
	MsgType_MsgTypeAudio MsgType = 3
	MsgType_MsgTypeVideo MsgType = 4
	MsgType_MsgTypeFile  MsgType = 5
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "MsgTypeNone",
		1: "MsgTypeText",
		2: "MsgTypeImage",
		3: "MsgTypeAudio",
		4: "MsgTypeVideo",
		5: "MsgTypeFile",
	}
	MsgType_value = map[string]int32{
		"MsgTypeNone":  0,
		"MsgTypeText":  1,
		"MsgTypeImage": 2,
		"MsgTypeAudio": 3,
		"MsgTypeVideo": 4,
		"MsgTypeFile":  5,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_pbentity_common_proto_enumTypes[1].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_pbentity_common_proto_enumTypes[1]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_pbentity_common_proto_rawDescGZIP(), []int{1}
}

// 翻译上面的结构定义为protobuf
type ModelAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer     string  `protobuf:"bytes,1,opt,name=Answer,proto3" json:"Answer,omitempty"`           //
	Score      int32   `protobuf:"varint,2,opt,name=Score,proto3" json:"Score,omitempty"`            //
	Error      string  `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`             //
	TokenCount int32   `protobuf:"varint,4,opt,name=TokenCount,proto3" json:"TokenCount,omitempty"`  //
	TokenPrice float64 `protobuf:"fixed64,5,opt,name=TokenPrice,proto3" json:"TokenPrice,omitempty"` //
}

func (x *ModelAnswer) Reset() {
	*x = ModelAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbentity_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelAnswer) ProtoMessage() {}

func (x *ModelAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelAnswer.ProtoReflect.Descriptor instead.
func (*ModelAnswer) Descriptor() ([]byte, []int) {
	return file_pbentity_common_proto_rawDescGZIP(), []int{0}
}

func (x *ModelAnswer) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *ModelAnswer) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ModelAnswer) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ModelAnswer) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *ModelAnswer) GetTokenPrice() float64 {
	if x != nil {
		return x.TokenPrice
	}
	return 0
}

type BotSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelId       string  `protobuf:"bytes,1,opt,name=ModelId,proto3" json:"ModelId,omitempty"` //
	Prompt        string  `protobuf:"bytes,2,opt,name=Prompt,proto3" json:"Prompt,omitempty"`   //
	Temperature   float32 `protobuf:"fixed32,4,opt,name=Temperature,proto3" json:"Temperature,omitempty"`
	MaxHistoryLen int32   `protobuf:"varint,3,opt,name=MaxHistoryLen,proto3" json:"MaxHistoryLen,omitempty"` //
}

func (x *BotSetting) Reset() {
	*x = BotSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbentity_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotSetting) ProtoMessage() {}

func (x *BotSetting) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotSetting.ProtoReflect.Descriptor instead.
func (*BotSetting) Descriptor() ([]byte, []int) {
	return file_pbentity_common_proto_rawDescGZIP(), []int{1}
}

func (x *BotSetting) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *BotSetting) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *BotSetting) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *BotSetting) GetMaxHistoryLen() int32 {
	if x != nil {
		return x.MaxHistoryLen
	}
	return 0
}

type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Q           *Message   `protobuf:"bytes,1,opt,name=Q,proto3" json:"Q,omitempty"`                     //
	HistoryMsgs []*Message `protobuf:"bytes,2,rep,name=HistoryMsgs,proto3" json:"HistoryMsgs,omitempty"` //
	SId         string     `protobuf:"bytes,3,opt,name=SId,proto3" json:"SId,omitempty"`
	UseStream   bool       `protobuf:"varint,4,opt,name=UseStream,proto3" json:"UseStream,omitempty"`
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbentity_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_pbentity_common_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetQ() *Message {
	if x != nil {
		return x.Q
	}
	return nil
}

func (x *Session) GetHistoryMsgs() []*Message {
	if x != nil {
		return x.HistoryMsgs
	}
	return nil
}

func (x *Session) GetSId() string {
	if x != nil {
		return x.SId
	}
	return ""
}

func (x *Session) GetUseStream() bool {
	if x != nil {
		return x.UseStream
	}
	return false
}

var File_pbentity_common_proto protoreflect.FileDescriptor

var file_pbentity_common_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x16, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x0b, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1e,
	0x0a, 0x0a, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0a, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x86,
	0x01, 0x0a, 0x0a, 0x42, 0x6f, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a,
	0x07, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x4d, 0x61, 0x78, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4c,
	0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x4d, 0x61, 0x78, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x4c, 0x65, 0x6e, 0x22, 0x8f, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x01, 0x51, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x01, 0x51, 0x12, 0x33, 0x0a, 0x0b, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d,
	0x73, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0b, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x55,
	0x73, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x55, 0x73, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2a, 0x45, 0x0a, 0x04, 0x52, 0x6f, 0x6c,
	0x65, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12,
	0x0e, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x10, 0x01, 0x12,
	0x0c, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x10, 0x02, 0x12, 0x11, 0x0a,
	0x0d, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x73, 0x73, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x10, 0x03,
	0x2a, 0x72, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x4d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x54, 0x65, 0x78, 0x74, 0x10, 0x01, 0x12, 0x10, 0x0a,
	0x0c, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x10, 0x02, 0x12,
	0x10, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x10,
	0x03, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x10, 0x05, 0x42, 0x14, 0x5a, 0x12, 0x31, 0x32, 0x33, 0x34, 0x35, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pbentity_common_proto_rawDescOnce sync.Once
	file_pbentity_common_proto_rawDescData = file_pbentity_common_proto_rawDesc
)

func file_pbentity_common_proto_rawDescGZIP() []byte {
	file_pbentity_common_proto_rawDescOnce.Do(func() {
		file_pbentity_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbentity_common_proto_rawDescData)
	})
	return file_pbentity_common_proto_rawDescData
}

var file_pbentity_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pbentity_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pbentity_common_proto_goTypes = []interface{}{
	(Role)(0),           // 0: pbentity.Role
	(MsgType)(0),        // 1: pbentity.MsgType
	(*ModelAnswer)(nil), // 2: pbentity.ModelAnswer
	(*BotSetting)(nil),  // 3: pbentity.BotSetting
	(*Session)(nil),     // 4: pbentity.Session
	(*Message)(nil),     // 5: pbentity.Message
}
var file_pbentity_common_proto_depIdxs = []int32{
	5, // 0: pbentity.Session.Q:type_name -> pbentity.Message
	5, // 1: pbentity.Session.HistoryMsgs:type_name -> pbentity.Message
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pbentity_common_proto_init() }
func file_pbentity_common_proto_init() {
	if File_pbentity_common_proto != nil {
		return
	}
	file_pbentity_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pbentity_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbentity_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbentity_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbentity_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_common_proto_goTypes,
		DependencyIndexes: file_pbentity_common_proto_depIdxs,
		EnumInfos:         file_pbentity_common_proto_enumTypes,
		MessageInfos:      file_pbentity_common_proto_msgTypes,
	}.Build()
	File_pbentity_common_proto = out.File
	file_pbentity_common_proto_rawDesc = nil
	file_pbentity_common_proto_goTypes = nil
	file_pbentity_common_proto_depIdxs = nil
}
