// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: pbentity/cost_detail.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CostDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`                //
	GroupId   string                 `protobuf:"bytes,2,opt,name=GroupId,proto3" json:"GroupId,omitempty"`      //
	OrgId     string                 `protobuf:"bytes,3,opt,name=OrgId,proto3" json:"OrgId,omitempty"`          //
	Uid       string                 `protobuf:"bytes,4,opt,name=Uid,proto3" json:"Uid,omitempty"`              //
	Tid       string                 `protobuf:"bytes,5,opt,name=Tid,proto3" json:"Tid,omitempty"`              //
	Sid       string                 `protobuf:"bytes,6,opt,name=Sid,proto3" json:"Sid,omitempty"`              //
	MsgId     string                 `protobuf:"bytes,7,opt,name=MsgId,proto3" json:"MsgId,omitempty"`          //
	Cost      int64                  `protobuf:"varint,8,opt,name=Cost,proto3" json:"Cost,omitempty"`           //
	Tokens    int64                  `protobuf:"varint,9,opt,name=Tokens,proto3" json:"Tokens,omitempty"`       //
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"` //
}

func (x *CostDetail) Reset() {
	*x = CostDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbentity_cost_detail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CostDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostDetail) ProtoMessage() {}

func (x *CostDetail) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_cost_detail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostDetail.ProtoReflect.Descriptor instead.
func (*CostDetail) Descriptor() ([]byte, []int) {
	return file_pbentity_cost_detail_proto_rawDescGZIP(), []int{0}
}

func (x *CostDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CostDetail) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CostDetail) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CostDetail) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CostDetail) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *CostDetail) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *CostDetail) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *CostDetail) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *CostDetail) GetTokens() int64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *CostDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_pbentity_cost_detail_proto protoreflect.FileDescriptor

var file_pbentity_cost_detail_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x63, 0x6f, 0x73, 0x74, 0x5f,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfe, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x73, 0x74,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x4f, 0x72, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x4f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4d, 0x73, 0x67,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x38,
	0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x14, 0x5a, 0x12, 0x31, 0x32, 0x33, 0x34,
	0x35, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbentity_cost_detail_proto_rawDescOnce sync.Once
	file_pbentity_cost_detail_proto_rawDescData = file_pbentity_cost_detail_proto_rawDesc
)

func file_pbentity_cost_detail_proto_rawDescGZIP() []byte {
	file_pbentity_cost_detail_proto_rawDescOnce.Do(func() {
		file_pbentity_cost_detail_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbentity_cost_detail_proto_rawDescData)
	})
	return file_pbentity_cost_detail_proto_rawDescData
}

var file_pbentity_cost_detail_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_cost_detail_proto_goTypes = []interface{}{
	(*CostDetail)(nil),            // 0: pbentity.CostDetail
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_cost_detail_proto_depIdxs = []int32{
	1, // 0: pbentity.CostDetail.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pbentity_cost_detail_proto_init() }
func file_pbentity_cost_detail_proto_init() {
	if File_pbentity_cost_detail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbentity_cost_detail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CostDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbentity_cost_detail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_cost_detail_proto_goTypes,
		DependencyIndexes: file_pbentity_cost_detail_proto_depIdxs,
		MessageInfos:      file_pbentity_cost_detail_proto_msgTypes,
	}.Build()
	File_pbentity_cost_detail_proto = out.File
	file_pbentity_cost_detail_proto_rawDesc = nil
	file_pbentity_cost_detail_proto_goTypes = nil
	file_pbentity_cost_detail_proto_depIdxs = nil
}
