// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: pbentity/uid.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`   //
	Org string `protobuf:"bytes,2,opt,name=Org,proto3" json:"Org,omitempty"` //
}

func (x *UID) Reset() {
	*x = UID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbentity_uid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UID) ProtoMessage() {}

func (x *UID) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_uid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UID.ProtoReflect.Descriptor instead.
func (*UID) Descriptor() ([]byte, []int) {
	return file_pbentity_uid_proto_rawDescGZIP(), []int{0}
}

func (x *UID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UID) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

var File_pbentity_uid_proto protoreflect.FileDescriptor

var file_pbentity_uid_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x75, 0x69, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x27, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4f, 0x72, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4f, 0x72, 0x67, 0x42, 0x14, 0x5a, 0x12, 0x31, 0x32, 0x33, 0x34,
	0x35, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbentity_uid_proto_rawDescOnce sync.Once
	file_pbentity_uid_proto_rawDescData = file_pbentity_uid_proto_rawDesc
)

func file_pbentity_uid_proto_rawDescGZIP() []byte {
	file_pbentity_uid_proto_rawDescOnce.Do(func() {
		file_pbentity_uid_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbentity_uid_proto_rawDescData)
	})
	return file_pbentity_uid_proto_rawDescData
}

var file_pbentity_uid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_uid_proto_goTypes = []interface{}{
	(*UID)(nil), // 0: pbentity.UID
}
var file_pbentity_uid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbentity_uid_proto_init() }
func file_pbentity_uid_proto_init() {
	if File_pbentity_uid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbentity_uid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbentity_uid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_uid_proto_goTypes,
		DependencyIndexes: file_pbentity_uid_proto_depIdxs,
		MessageInfos:      file_pbentity_uid_proto_msgTypes,
	}.Build()
	File_pbentity_uid_proto = out.File
	file_pbentity_uid_proto_rawDesc = nil
	file_pbentity_uid_proto_goTypes = nil
	file_pbentity_uid_proto_depIdxs = nil
}
