// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"12345/internal/dao/internal"
)

// internalBotDao is internal type for wrapping internal DAO implements.
type internalBotDao = *internal.BotDao

// botDao is the data access object for table bot.
// You can define custom methods on it to extend its functionality as you wish.
type botDao struct {
	internalBotDao
}

var (
	// Bot is globally public accessible object for table bot operations.
	Bot = botDao{
		internal.NewBotDao(),
	}
)

// Fill with you ideas below.
