// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"12345/internal/dao/internal"
)

// internalCostDetailDao is internal type for wrapping internal DAO implements.
type internalCostDetailDao = *internal.CostDetailDao

// costDetailDao is the data access object for table cost_detail.
// You can define custom methods on it to extend its functionality as you wish.
type costDetailDao struct {
	internalCostDetailDao
}

var (
	// CostDetail is globally public accessible object for table cost_detail operations.
	CostDetail = costDetailDao{
		internal.NewCostDetailDao(),
	}
)

// Fill with you ideas below.
