// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"12345/internal/dao/internal"
)

// internalDialogDao is internal type for wrapping internal DAO implements.
type internalDialogDao = *internal.DialogDao

// dialogDao is the data access object for table dialog.
// You can define custom methods on it to extend its functionality as you wish.
type dialogDao struct {
	internalDialogDao
}

var (
	// Dialog is globally public accessible object for table dialog operations.
	Dialog = dialogDao{
		internal.NewDialogDao(),
	}
)

// Fill with you ideas below.
