// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"12345/internal/dao/internal"
)

// internalSessionDao is internal type for wrapping internal DAO implements.
type internalSessionDao = *internal.SessionDao

// sessionDao is the data access object for table session.
// You can define custom methods on it to extend its functionality as you wish.
type sessionDao struct {
	internalSessionDao
}

var (
	// Session is globally public accessible object for table session operations.
	Session = sessionDao{
		internal.NewSessionDao(),
	}
)

// Fill with you ideas below.
