// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"12345/internal/dao/internal"
)

// internalUprofileDao is internal type for wrapping internal DAO implements.
type internalUprofileDao = *internal.UprofileDao

// uprofileDao is the data access object for table uprofile.
// You can define custom methods on it to extend its functionality as you wish.
type uprofileDao struct {
	internalUprofileDao
}

var (
	// Uprofile is globally public accessible object for table uprofile operations.
	Uprofile = uprofileDao{
		internal.NewUprofileDao(),
	}
)

// Fill with you ideas below.
