// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: grpc/v1/api.proto

package v1

import (
	pbentity "12345/api/pbentity"
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *ErrCode) Reset() {
	*x = ErrCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrCode) ProtoMessage() {}

func (x *ErrCode) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrCode.ProtoReflect.Descriptor instead.
func (*ErrCode) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *ErrCode) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrCode) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CommonRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EC *ErrCode `protobuf:"bytes,1,opt,name=EC,proto3" json:"EC,omitempty"`
}

func (x *CommonRes) Reset() {
	*x = CommonRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRes) ProtoMessage() {}

func (x *CommonRes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRes.ProtoReflect.Descriptor instead.
func (*CommonRes) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *CommonRes) GetEC() *ErrCode {
	if x != nil {
		return x.EC
	}
	return nil
}

// tool ------------------------------------------------------------------------
type CreateToolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tool *pbentity.Tool `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
}

func (x *CreateToolRequest) Reset() {
	*x = CreateToolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateToolRequest) ProtoMessage() {}

func (x *CreateToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateToolRequest.ProtoReflect.Descriptor instead.
func (*CreateToolRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateToolRequest) GetTool() *pbentity.Tool {
	if x != nil {
		return x.Tool
	}
	return nil
}

type CreateToolResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EC   *ErrCode       `protobuf:"bytes,1,opt,name=EC,proto3" json:"EC,omitempty"`
	Tool *pbentity.Tool `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
}

func (x *CreateToolResponse) Reset() {
	*x = CreateToolResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateToolResponse) ProtoMessage() {}

func (x *CreateToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateToolResponse.ProtoReflect.Descriptor instead.
func (*CreateToolResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *CreateToolResponse) GetEC() *ErrCode {
	if x != nil {
		return x.EC
	}
	return nil
}

func (x *CreateToolResponse) GetTool() *pbentity.Tool {
	if x != nil {
		return x.Tool
	}
	return nil
}

type GetToolListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	From string `protobuf:"bytes,3,opt,name=From,proto3" json:"From,omitempty"`
}

func (x *GetToolListRequest) Reset() {
	*x = GetToolListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetToolListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolListRequest) ProtoMessage() {}

func (x *GetToolListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolListRequest.ProtoReflect.Descriptor instead.
func (*GetToolListRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetToolListRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetToolListRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type GetToolListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EC    *ErrCode         `protobuf:"bytes,1,opt,name=EC,proto3" json:"EC,omitempty"`
	Tools []*pbentity.Tool `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
}

func (x *GetToolListResponse) Reset() {
	*x = GetToolListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetToolListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolListResponse) ProtoMessage() {}

func (x *GetToolListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolListResponse.ProtoReflect.Descriptor instead.
func (*GetToolListResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetToolListResponse) GetEC() *ErrCode {
	if x != nil {
		return x.EC
	}
	return nil
}

func (x *GetToolListResponse) GetTools() []*pbentity.Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

type DelToolsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=Ids,proto3" json:"Ids,omitempty"`
}

func (x *DelToolsRequest) Reset() {
	*x = DelToolsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelToolsRequest) ProtoMessage() {}

func (x *DelToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelToolsRequest.ProtoReflect.Descriptor instead.
func (*DelToolsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *DelToolsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DelToolsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EC *ErrCode `protobuf:"bytes,1,opt,name=EC,proto3" json:"EC,omitempty"`
}

func (x *DelToolsResponse) Reset() {
	*x = DelToolsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelToolsResponse) ProtoMessage() {}

func (x *DelToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelToolsResponse.ProtoReflect.Descriptor instead.
func (*DelToolsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{7}
}

func (x *DelToolsResponse) GetEC() *ErrCode {
	if x != nil {
		return x.EC
	}
	return nil
}

type CallToolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Stream bool   `protobuf:"varint,2,opt,name=stream,proto3" json:"stream,omitempty"`
}

func (x *CallToolRequest) Reset() {
	*x = CallToolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolRequest) ProtoMessage() {}

func (x *CallToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolRequest.ProtoReflect.Descriptor instead.
func (*CallToolRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{8}
}

func (x *CallToolRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CallToolRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

type CallToolResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EC *ErrCode `protobuf:"bytes,1,opt,name=EC,proto3" json:"EC,omitempty"`
	// object
	Data *anypb.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty" dc:"object"` //
}

func (x *CallToolResponse) Reset() {
	*x = CallToolResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolResponse) ProtoMessage() {}

func (x *CallToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolResponse.ProtoReflect.Descriptor instead.
func (*CallToolResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{9}
}

func (x *CallToolResponse) GetEC() *ErrCode {
	if x != nil {
		return x.EC
	}
	return nil
}

func (x *CallToolResponse) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

// dialog --------------------------------------------------------------------------
type GetDialogListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId      string `protobuf:"bytes,1,opt,name=UId,proto3" json:"UId,omitempty"`
	OId      string `protobuf:"bytes,2,opt,name=OId,proto3" json:"OId,omitempty"`
	Page     int32  `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize int32  `protobuf:"varint,4,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *GetDialogListRequest) Reset() {
	*x = GetDialogListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDialogListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDialogListRequest) ProtoMessage() {}

func (x *GetDialogListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDialogListRequest.ProtoReflect.Descriptor instead.
func (*GetDialogListRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetDialogListRequest) GetUId() string {
	if x != nil {
		return x.UId
	}
	return ""
}

func (x *GetDialogListRequest) GetOId() string {
	if x != nil {
		return x.OId
	}
	return ""
}

func (x *GetDialogListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDialogListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetDialogListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EC      *ErrCode           `protobuf:"bytes,1,opt,name=EC,proto3" json:"EC,omitempty"`
	Dialogs []*pbentity.Dialog `protobuf:"bytes,2,rep,name=Dialogs,proto3" json:"Dialogs,omitempty"`
}

func (x *GetDialogListResponse) Reset() {
	*x = GetDialogListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDialogListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDialogListResponse) ProtoMessage() {}

func (x *GetDialogListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDialogListResponse.ProtoReflect.Descriptor instead.
func (*GetDialogListResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{11}
}

func (x *GetDialogListResponse) GetEC() *ErrCode {
	if x != nil {
		return x.EC
	}
	return nil
}

func (x *GetDialogListResponse) GetDialogs() []*pbentity.Dialog {
	if x != nil {
		return x.Dialogs
	}
	return nil
}

type GetDialogDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId string `protobuf:"bytes,1,opt,name=UId,proto3" json:"UId,omitempty"`
	OId string `protobuf:"bytes,2,opt,name=OId,proto3" json:"OId,omitempty"`
	SId string `protobuf:"bytes,3,opt,name=SId,proto3" json:"SId,omitempty"`
}

func (x *GetDialogDetailRequest) Reset() {
	*x = GetDialogDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDialogDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDialogDetailRequest) ProtoMessage() {}

func (x *GetDialogDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDialogDetailRequest.ProtoReflect.Descriptor instead.
func (*GetDialogDetailRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{12}
}

func (x *GetDialogDetailRequest) GetUId() string {
	if x != nil {
		return x.UId
	}
	return ""
}

func (x *GetDialogDetailRequest) GetOId() string {
	if x != nil {
		return x.OId
	}
	return ""
}

func (x *GetDialogDetailRequest) GetSId() string {
	if x != nil {
		return x.SId
	}
	return ""
}

type GetDialogDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EC     *ErrCode         `protobuf:"bytes,1,opt,name=EC,proto3" json:"EC,omitempty"`
	Dialog *pbentity.Dialog `protobuf:"bytes,2,opt,name=Dialog,proto3" json:"Dialog,omitempty"`
}

func (x *GetDialogDetailResponse) Reset() {
	*x = GetDialogDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDialogDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDialogDetailResponse) ProtoMessage() {}

func (x *GetDialogDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDialogDetailResponse.ProtoReflect.Descriptor instead.
func (*GetDialogDetailResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{13}
}

func (x *GetDialogDetailResponse) GetEC() *ErrCode {
	if x != nil {
		return x.EC
	}
	return nil
}

func (x *GetDialogDetailResponse) GetDialog() *pbentity.Dialog {
	if x != nil {
		return x.Dialog
	}
	return nil
}

type AddDialogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId   string `protobuf:"bytes,1,opt,name=UId,proto3" json:"UId,omitempty"`
	OId   string `protobuf:"bytes,2,opt,name=OId,proto3" json:"OId,omitempty"`
	Id    string `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	Title string `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`
}

func (x *AddDialogRequest) Reset() {
	*x = AddDialogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDialogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDialogRequest) ProtoMessage() {}

func (x *AddDialogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDialogRequest.ProtoReflect.Descriptor instead.
func (*AddDialogRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{14}
}

func (x *AddDialogRequest) GetUId() string {
	if x != nil {
		return x.UId
	}
	return ""
}

func (x *AddDialogRequest) GetOId() string {
	if x != nil {
		return x.OId
	}
	return ""
}

func (x *AddDialogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddDialogRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type AddDialogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EC     *ErrCode         `protobuf:"bytes,1,opt,name=EC,proto3" json:"EC,omitempty"`
	Dialog *pbentity.Dialog `protobuf:"bytes,2,opt,name=Dialog,proto3" json:"Dialog,omitempty"`
}

func (x *AddDialogResponse) Reset() {
	*x = AddDialogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDialogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDialogResponse) ProtoMessage() {}

func (x *AddDialogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDialogResponse.ProtoReflect.Descriptor instead.
func (*AddDialogResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{15}
}

func (x *AddDialogResponse) GetEC() *ErrCode {
	if x != nil {
		return x.EC
	}
	return nil
}

func (x *AddDialogResponse) GetDialog() *pbentity.Dialog {
	if x != nil {
		return x.Dialog
	}
	return nil
}

type DelDialogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId string `protobuf:"bytes,1,opt,name=UId,proto3" json:"UId,omitempty"`
	OId string `protobuf:"bytes,2,opt,name=OId,proto3" json:"OId,omitempty"`
	SId string `protobuf:"bytes,3,opt,name=SId,proto3" json:"SId,omitempty"`
}

func (x *DelDialogRequest) Reset() {
	*x = DelDialogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelDialogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelDialogRequest) ProtoMessage() {}

func (x *DelDialogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelDialogRequest.ProtoReflect.Descriptor instead.
func (*DelDialogRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{16}
}

func (x *DelDialogRequest) GetUId() string {
	if x != nil {
		return x.UId
	}
	return ""
}

func (x *DelDialogRequest) GetOId() string {
	if x != nil {
		return x.OId
	}
	return ""
}

func (x *DelDialogRequest) GetSId() string {
	if x != nil {
		return x.SId
	}
	return ""
}

type DelDialogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EC *ErrCode `protobuf:"bytes,1,opt,name=EC,proto3" json:"EC,omitempty"`
}

func (x *DelDialogResponse) Reset() {
	*x = DelDialogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelDialogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelDialogResponse) ProtoMessage() {}

func (x *DelDialogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelDialogResponse.ProtoReflect.Descriptor instead.
func (*DelDialogResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{17}
}

func (x *DelDialogResponse) GetEC() *ErrCode {
	if x != nil {
		return x.EC
	}
	return nil
}

type GetDialogMsgListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId      string `protobuf:"bytes,1,opt,name=UId,proto3" json:"UId,omitempty"`
	OId      string `protobuf:"bytes,2,opt,name=OId,proto3" json:"OId,omitempty"`
	SId      string `protobuf:"bytes,3,opt,name=SId,proto3" json:"SId,omitempty"`
	Page     int32  `protobuf:"varint,4,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize int32  `protobuf:"varint,5,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *GetDialogMsgListRequest) Reset() {
	*x = GetDialogMsgListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDialogMsgListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDialogMsgListRequest) ProtoMessage() {}

func (x *GetDialogMsgListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDialogMsgListRequest.ProtoReflect.Descriptor instead.
func (*GetDialogMsgListRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{18}
}

func (x *GetDialogMsgListRequest) GetUId() string {
	if x != nil {
		return x.UId
	}
	return ""
}

func (x *GetDialogMsgListRequest) GetOId() string {
	if x != nil {
		return x.OId
	}
	return ""
}

func (x *GetDialogMsgListRequest) GetSId() string {
	if x != nil {
		return x.SId
	}
	return ""
}

func (x *GetDialogMsgListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDialogMsgListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetDialogMsgListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EC   *ErrCode            `protobuf:"bytes,1,opt,name=EC,proto3" json:"EC,omitempty"`
	Msgs []*pbentity.Message `protobuf:"bytes,2,rep,name=Msgs,proto3" json:"Msgs,omitempty"`
}

func (x *GetDialogMsgListResponse) Reset() {
	*x = GetDialogMsgListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDialogMsgListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDialogMsgListResponse) ProtoMessage() {}

func (x *GetDialogMsgListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDialogMsgListResponse.ProtoReflect.Descriptor instead.
func (*GetDialogMsgListResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{19}
}

func (x *GetDialogMsgListResponse) GetEC() *ErrCode {
	if x != nil {
		return x.EC
	}
	return nil
}

func (x *GetDialogMsgListResponse) GetMsgs() []*pbentity.Message {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type AddDialogMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId string            `protobuf:"bytes,1,opt,name=UId,proto3" json:"UId,omitempty"`
	OId string            `protobuf:"bytes,2,opt,name=OId,proto3" json:"OId,omitempty"`
	SId string            `protobuf:"bytes,3,opt,name=SId,proto3" json:"SId,omitempty"`
	Msg *pbentity.Message `protobuf:"bytes,4,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *AddDialogMsgRequest) Reset() {
	*x = AddDialogMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDialogMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDialogMsgRequest) ProtoMessage() {}

func (x *AddDialogMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDialogMsgRequest.ProtoReflect.Descriptor instead.
func (*AddDialogMsgRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{20}
}

func (x *AddDialogMsgRequest) GetUId() string {
	if x != nil {
		return x.UId
	}
	return ""
}

func (x *AddDialogMsgRequest) GetOId() string {
	if x != nil {
		return x.OId
	}
	return ""
}

func (x *AddDialogMsgRequest) GetSId() string {
	if x != nil {
		return x.SId
	}
	return ""
}

func (x *AddDialogMsgRequest) GetMsg() *pbentity.Message {
	if x != nil {
		return x.Msg
	}
	return nil
}

type AddDialogMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EC  *ErrCode          `protobuf:"bytes,1,opt,name=EC,proto3" json:"EC,omitempty"`
	Msg *pbentity.Message `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *AddDialogMsgResponse) Reset() {
	*x = AddDialogMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDialogMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDialogMsgResponse) ProtoMessage() {}

func (x *AddDialogMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDialogMsgResponse.ProtoReflect.Descriptor instead.
func (*AddDialogMsgResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{21}
}

func (x *AddDialogMsgResponse) GetEC() *ErrCode {
	if x != nil {
		return x.EC
	}
	return nil
}

func (x *AddDialogMsgResponse) GetMsg() *pbentity.Message {
	if x != nil {
		return x.Msg
	}
	return nil
}

// profile -----------------------------------------------------------------------------------
type GetProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{22}
}

type GetProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EC      *ErrCode           `protobuf:"bytes,1,opt,name=EC,proto3" json:"EC,omitempty"`
	Profile *pbentity.Uprofile `protobuf:"bytes,2,opt,name=Profile,proto3" json:"Profile,omitempty"`
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{23}
}

func (x *GetProfileResponse) GetEC() *ErrCode {
	if x != nil {
		return x.EC
	}
	return nil
}

func (x *GetProfileResponse) GetProfile() *pbentity.Uprofile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profile *pbentity.Uprofile `protobuf:"bytes,1,opt,name=Profile,proto3" json:"Profile,omitempty"`
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateProfileRequest) GetProfile() *pbentity.Uprofile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EC *ErrCode `protobuf:"bytes,1,opt,name=EC,proto3" json:"EC,omitempty"`
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateProfileResponse) GetEC() *ErrCode {
	if x != nil {
		return x.EC
	}
	return nil
}

// account --------------------------------------------------------------------------------
type GetAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{26}
}

type GetAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EC      *ErrCode          `protobuf:"bytes,1,opt,name=EC,proto3" json:"EC,omitempty"`
	Account *pbentity.Account `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{27}
}

func (x *GetAccountResponse) GetEC() *ErrCode {
	if x != nil {
		return x.EC
	}
	return nil
}

func (x *GetAccountResponse) GetAccount() *pbentity.Account {
	if x != nil {
		return x.Account
	}
	return nil
}

// store --------------------------------------------------------------------------------
type PreSignedUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjName string `protobuf:"bytes,1,opt,name=objName,proto3" json:"objName,omitempty"`
}

func (x *PreSignedUrlRequest) Reset() {
	*x = PreSignedUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreSignedUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSignedUrlRequest) ProtoMessage() {}

func (x *PreSignedUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSignedUrlRequest.ProtoReflect.Descriptor instead.
func (*PreSignedUrlRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{28}
}

func (x *PreSignedUrlRequest) GetObjName() string {
	if x != nil {
		return x.ObjName
	}
	return ""
}

type PreSignedUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EC     *ErrCode `protobuf:"bytes,1,opt,name=EC,proto3" json:"EC,omitempty"`
	PutUrl string   `protobuf:"bytes,2,opt,name=putUrl,proto3" json:"putUrl,omitempty"`
	Url    string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *PreSignedUrlResponse) Reset() {
	*x = PreSignedUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_v1_api_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreSignedUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSignedUrlResponse) ProtoMessage() {}

func (x *PreSignedUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_api_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSignedUrlResponse.ProtoReflect.Descriptor instead.
func (*PreSignedUrlResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_api_proto_rawDescGZIP(), []int{29}
}

func (x *PreSignedUrlResponse) GetEC() *ErrCode {
	if x != nil {
		return x.EC
	}
	return nil
}

func (x *PreSignedUrlResponse) GetPutUrl() string {
	if x != nil {
		return x.PutUrl
	}
	return ""
}

func (x *PreSignedUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_grpc_v1_api_proto protoreflect.FileDescriptor

var file_grpc_v1_api_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x70, 0x62,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x64,
	0x69, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x70, 0x62, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x17, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x75, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x70, 0x62, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x2f, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x73, 0x67, 0x22, 0x2a, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12,
	0x1d, 0x0a, 0x02, 0x45, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x02, 0x45, 0x43, 0x22, 0x37,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x6f, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x54, 0x6f, 0x6f,
	0x6c, 0x52, 0x04, 0x74, 0x6f, 0x6f, 0x6c, 0x22, 0x57, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a,
	0x02, 0x45, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x02, 0x45, 0x43, 0x12, 0x22, 0x0a, 0x04,
	0x74, 0x6f, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x52, 0x04, 0x74, 0x6f, 0x6f, 0x6c,
	0x22, 0x3c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72,
	0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x22, 0x5a,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x02, 0x45, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x02, 0x45, 0x43, 0x12, 0x24, 0x0a, 0x05, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x54,
	0x6f, 0x6f, 0x6c, 0x52, 0x05, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x22, 0x23, 0x0a, 0x0f, 0x44, 0x65,
	0x6c, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x49, 0x64, 0x73, 0x22,
	0x31, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x02, 0x45, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x02,
	0x45, 0x43, 0x22, 0x39, 0x0a, 0x0f, 0x43, 0x61, 0x6c, 0x6c, 0x54, 0x6f, 0x6f, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x5b, 0x0a,
	0x10, 0x43, 0x61, 0x6c, 0x6c, 0x54, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1d, 0x0a, 0x02, 0x45, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x02, 0x45, 0x43,
	0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6a, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x55, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4f, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4f, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x50, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x62, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61,
	0x6c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1d, 0x0a, 0x02, 0x45, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x02, 0x45, 0x43, 0x12, 0x2a,
	0x0a, 0x07, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f,
	0x67, 0x52, 0x07, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x4e, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4f, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4f, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x49, 0x64, 0x22, 0x62, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x02, 0x45, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x02, 0x45, 0x43, 0x12, 0x28, 0x0a, 0x06, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x06, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x22, 0x5c,
	0x0a, 0x10, 0x41, 0x64, 0x64, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x55, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4f, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4f, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x5c, 0x0a, 0x11,
	0x41, 0x64, 0x64, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1d, 0x0a, 0x02, 0x45, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x02, 0x45, 0x43,
	0x12, 0x28, 0x0a, 0x06, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x44, 0x69, 0x61, 0x6c,
	0x6f, 0x67, 0x52, 0x06, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x22, 0x48, 0x0a, 0x10, 0x44, 0x65,
	0x6c, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x4f, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4f,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x53, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x44, 0x69, 0x61, 0x6c, 0x6f,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x02, 0x45, 0x43, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x02, 0x45, 0x43, 0x22, 0x7f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x44,
	0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4f, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4f, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x60, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x02, 0x45, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x02, 0x45, 0x43, 0x12, 0x25, 0x0a, 0x04, 0x4d, 0x73, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x4d, 0x73, 0x67, 0x73, 0x22, 0x70, 0x0a, 0x13, 0x41,
	0x64, 0x64, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x55, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4f, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4f, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x5a, 0x0a,
	0x14, 0x41, 0x64, 0x64, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x02, 0x45, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x02, 0x45, 0x43, 0x12, 0x23, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x61,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x02, 0x45, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x02, 0x45, 0x43, 0x12, 0x2c, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x55, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x22, 0x44, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x55, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x36, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x02, 0x45, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x02, 0x45, 0x43, 0x22,
	0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x60, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x02, 0x45, 0x43,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x02, 0x45, 0x43, 0x12, 0x2b, 0x0a, 0x07, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2f, 0x0a, 0x13, 0x50, 0x72, 0x65, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x6f, 0x62, 0x6a, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x62, 0x6a, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5f, 0x0a, 0x14, 0x50, 0x72, 0x65, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x64, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1d, 0x0a, 0x02, 0x45, 0x43, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x02, 0x45, 0x43, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x75, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x75, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x32, 0xc7, 0x07, 0x0a, 0x0a, 0x41, 0x70, 0x69,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6f, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54,
	0x6f, 0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6f, 0x6c,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x08,
	0x44, 0x65, 0x6c, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x12, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x44, 0x65, 0x6c, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x43, 0x61, 0x6c, 0x6c, 0x54,
	0x6f, 0x6f, 0x6c, 0x12, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x54,
	0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x54, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x55,
	0x72, 0x6c, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x65, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x55, 0x72,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0c, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x12, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x41, 0x64, 0x64, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x69, 0x61, 0x6c,
	0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f,
	0x67, 0x12, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x6c,
	0x6f, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c,
	0x0a, 0x09, 0x44, 0x65, 0x6c, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x12, 0x16, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x44, 0x69,
	0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f,
	0x67, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67,
	0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x45, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4d, 0x73, 0x67, 0x12,
	0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4d, 0x73, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x31, 0x32, 0x33, 0x34, 0x35, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_v1_api_proto_rawDescOnce sync.Once
	file_grpc_v1_api_proto_rawDescData = file_grpc_v1_api_proto_rawDesc
)

func file_grpc_v1_api_proto_rawDescGZIP() []byte {
	file_grpc_v1_api_proto_rawDescOnce.Do(func() {
		file_grpc_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_v1_api_proto_rawDescData)
	})
	return file_grpc_v1_api_proto_rawDescData
}

var file_grpc_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_grpc_v1_api_proto_goTypes = []interface{}{
	(*ErrCode)(nil),                  // 0: grpc.ErrCode
	(*CommonRes)(nil),                // 1: grpc.CommonRes
	(*CreateToolRequest)(nil),        // 2: grpc.CreateToolRequest
	(*CreateToolResponse)(nil),       // 3: grpc.CreateToolResponse
	(*GetToolListRequest)(nil),       // 4: grpc.GetToolListRequest
	(*GetToolListResponse)(nil),      // 5: grpc.GetToolListResponse
	(*DelToolsRequest)(nil),          // 6: grpc.DelToolsRequest
	(*DelToolsResponse)(nil),         // 7: grpc.DelToolsResponse
	(*CallToolRequest)(nil),          // 8: grpc.CallToolRequest
	(*CallToolResponse)(nil),         // 9: grpc.CallToolResponse
	(*GetDialogListRequest)(nil),     // 10: grpc.GetDialogListRequest
	(*GetDialogListResponse)(nil),    // 11: grpc.GetDialogListResponse
	(*GetDialogDetailRequest)(nil),   // 12: grpc.GetDialogDetailRequest
	(*GetDialogDetailResponse)(nil),  // 13: grpc.GetDialogDetailResponse
	(*AddDialogRequest)(nil),         // 14: grpc.AddDialogRequest
	(*AddDialogResponse)(nil),        // 15: grpc.AddDialogResponse
	(*DelDialogRequest)(nil),         // 16: grpc.DelDialogRequest
	(*DelDialogResponse)(nil),        // 17: grpc.DelDialogResponse
	(*GetDialogMsgListRequest)(nil),  // 18: grpc.GetDialogMsgListRequest
	(*GetDialogMsgListResponse)(nil), // 19: grpc.GetDialogMsgListResponse
	(*AddDialogMsgRequest)(nil),      // 20: grpc.AddDialogMsgRequest
	(*AddDialogMsgResponse)(nil),     // 21: grpc.AddDialogMsgResponse
	(*GetProfileRequest)(nil),        // 22: grpc.GetProfileRequest
	(*GetProfileResponse)(nil),       // 23: grpc.GetProfileResponse
	(*UpdateProfileRequest)(nil),     // 24: grpc.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),    // 25: grpc.UpdateProfileResponse
	(*GetAccountRequest)(nil),        // 26: grpc.GetAccountRequest
	(*GetAccountResponse)(nil),       // 27: grpc.GetAccountResponse
	(*PreSignedUrlRequest)(nil),      // 28: grpc.PreSignedUrlRequest
	(*PreSignedUrlResponse)(nil),     // 29: grpc.PreSignedUrlResponse
	(*pbentity.Tool)(nil),            // 30: pbentity.Tool
	(*anypb.Any)(nil),                // 31: google.protobuf.Any
	(*pbentity.Dialog)(nil),          // 32: pbentity.Dialog
	(*pbentity.Message)(nil),         // 33: pbentity.Message
	(*pbentity.Uprofile)(nil),        // 34: pbentity.Uprofile
	(*pbentity.Account)(nil),         // 35: pbentity.Account
}
var file_grpc_v1_api_proto_depIdxs = []int32{
	0,  // 0: grpc.CommonRes.EC:type_name -> grpc.ErrCode
	30, // 1: grpc.CreateToolRequest.tool:type_name -> pbentity.Tool
	0,  // 2: grpc.CreateToolResponse.EC:type_name -> grpc.ErrCode
	30, // 3: grpc.CreateToolResponse.tool:type_name -> pbentity.Tool
	0,  // 4: grpc.GetToolListResponse.EC:type_name -> grpc.ErrCode
	30, // 5: grpc.GetToolListResponse.tools:type_name -> pbentity.Tool
	0,  // 6: grpc.DelToolsResponse.EC:type_name -> grpc.ErrCode
	0,  // 7: grpc.CallToolResponse.EC:type_name -> grpc.ErrCode
	31, // 8: grpc.CallToolResponse.data:type_name -> google.protobuf.Any
	0,  // 9: grpc.GetDialogListResponse.EC:type_name -> grpc.ErrCode
	32, // 10: grpc.GetDialogListResponse.Dialogs:type_name -> pbentity.Dialog
	0,  // 11: grpc.GetDialogDetailResponse.EC:type_name -> grpc.ErrCode
	32, // 12: grpc.GetDialogDetailResponse.Dialog:type_name -> pbentity.Dialog
	0,  // 13: grpc.AddDialogResponse.EC:type_name -> grpc.ErrCode
	32, // 14: grpc.AddDialogResponse.Dialog:type_name -> pbentity.Dialog
	0,  // 15: grpc.DelDialogResponse.EC:type_name -> grpc.ErrCode
	0,  // 16: grpc.GetDialogMsgListResponse.EC:type_name -> grpc.ErrCode
	33, // 17: grpc.GetDialogMsgListResponse.Msgs:type_name -> pbentity.Message
	33, // 18: grpc.AddDialogMsgRequest.Msg:type_name -> pbentity.Message
	0,  // 19: grpc.AddDialogMsgResponse.EC:type_name -> grpc.ErrCode
	33, // 20: grpc.AddDialogMsgResponse.Msg:type_name -> pbentity.Message
	0,  // 21: grpc.GetProfileResponse.EC:type_name -> grpc.ErrCode
	34, // 22: grpc.GetProfileResponse.Profile:type_name -> pbentity.Uprofile
	34, // 23: grpc.UpdateProfileRequest.Profile:type_name -> pbentity.Uprofile
	0,  // 24: grpc.UpdateProfileResponse.EC:type_name -> grpc.ErrCode
	0,  // 25: grpc.GetAccountResponse.EC:type_name -> grpc.ErrCode
	35, // 26: grpc.GetAccountResponse.Account:type_name -> pbentity.Account
	0,  // 27: grpc.PreSignedUrlResponse.EC:type_name -> grpc.ErrCode
	2,  // 28: grpc.ApiService.CreateTool:input_type -> grpc.CreateToolRequest
	4,  // 29: grpc.ApiService.GetToolList:input_type -> grpc.GetToolListRequest
	6,  // 30: grpc.ApiService.DelTools:input_type -> grpc.DelToolsRequest
	8,  // 31: grpc.ApiService.CallTool:input_type -> grpc.CallToolRequest
	28, // 32: grpc.ApiService.PreSignedUrl:input_type -> grpc.PreSignedUrlRequest
	14, // 33: grpc.ApiService.CreateDialog:input_type -> grpc.AddDialogRequest
	10, // 34: grpc.ApiService.GetDialogList:input_type -> grpc.GetDialogListRequest
	12, // 35: grpc.ApiService.GetDialog:input_type -> grpc.GetDialogDetailRequest
	16, // 36: grpc.ApiService.DelDialog:input_type -> grpc.DelDialogRequest
	18, // 37: grpc.ApiService.GetDialogMsgList:input_type -> grpc.GetDialogMsgListRequest
	20, // 38: grpc.ApiService.AddDialogMsg:input_type -> grpc.AddDialogMsgRequest
	22, // 39: grpc.ApiService.GetProfile:input_type -> grpc.GetProfileRequest
	24, // 40: grpc.ApiService.UpdateProfile:input_type -> grpc.UpdateProfileRequest
	26, // 41: grpc.ApiService.GetAccount:input_type -> grpc.GetAccountRequest
	3,  // 42: grpc.ApiService.CreateTool:output_type -> grpc.CreateToolResponse
	5,  // 43: grpc.ApiService.GetToolList:output_type -> grpc.GetToolListResponse
	7,  // 44: grpc.ApiService.DelTools:output_type -> grpc.DelToolsResponse
	9,  // 45: grpc.ApiService.CallTool:output_type -> grpc.CallToolResponse
	29, // 46: grpc.ApiService.PreSignedUrl:output_type -> grpc.PreSignedUrlResponse
	15, // 47: grpc.ApiService.CreateDialog:output_type -> grpc.AddDialogResponse
	11, // 48: grpc.ApiService.GetDialogList:output_type -> grpc.GetDialogListResponse
	13, // 49: grpc.ApiService.GetDialog:output_type -> grpc.GetDialogDetailResponse
	17, // 50: grpc.ApiService.DelDialog:output_type -> grpc.DelDialogResponse
	19, // 51: grpc.ApiService.GetDialogMsgList:output_type -> grpc.GetDialogMsgListResponse
	21, // 52: grpc.ApiService.AddDialogMsg:output_type -> grpc.AddDialogMsgResponse
	23, // 53: grpc.ApiService.GetProfile:output_type -> grpc.GetProfileResponse
	25, // 54: grpc.ApiService.UpdateProfile:output_type -> grpc.UpdateProfileResponse
	27, // 55: grpc.ApiService.GetAccount:output_type -> grpc.GetAccountResponse
	42, // [42:56] is the sub-list for method output_type
	28, // [28:42] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_grpc_v1_api_proto_init() }
func file_grpc_v1_api_proto_init() {
	if File_grpc_v1_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_v1_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateToolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateToolResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetToolListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetToolListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelToolsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelToolsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallToolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallToolResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDialogListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDialogListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDialogDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDialogDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDialogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDialogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelDialogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelDialogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDialogMsgListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDialogMsgListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDialogMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDialogMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreSignedUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_v1_api_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreSignedUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_v1_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_v1_api_proto_goTypes,
		DependencyIndexes: file_grpc_v1_api_proto_depIdxs,
		MessageInfos:      file_grpc_v1_api_proto_msgTypes,
	}.Build()
	File_grpc_v1_api_proto = out.File
	file_grpc_v1_api_proto_rawDesc = nil
	file_grpc_v1_api_proto_goTypes = nil
	file_grpc_v1_api_proto_depIdxs = nil
}
